### ISSUE TITLE
Does not fit on screen

### ISSUE THREAD

**Issue by ghandhikus** [ChaonicTheDeathKitten/Palette-Helper#1]
Hey it does not seem to fit on the screen with the settings below:

![image](https://user-images.githubusercontent.com/5513498/206035444-fc36169c-eeec-4c44-be7f-e131d58f3dfa.png)

![image](https://user-images.githubusercontent.com/5513498/206035339-82a2ac5a-214c-493e-b9b3-785f3fe7f78b.png)

**Comment by ghandhikus** [comment]
1920x1080 screen, maximized btw

**Comment by ChaonicTheDeathKitten** [comment]
I'm so sorry, I didn't read it until now.
I have tested my script against my 1080p screen and it fit perfectly on the screen.
What seems to me is that the issue might lie in the UI scale and the theme you're using.
That being said, the latest version is not going to have the same problem. The window is split into a main one and one for advanced settings that's optional.
