### ISSUE TITLE
Reset: Soft Hues

### ISSUE THREAD

**Issue by topnik-code** [ChaonicTheDeathKitten/Palette-Helper#2]
Just a tiny bug: clicking "Reset" does not change the amount of "Soft Hues".

Amazing script, please keep up the good work! 👍

**Comment by ChaonicTheDeathKitten** [comment]
I'm so sorry for this, I never looked into the issues here.
You're absolutely right, the Soft Hues were never included in the Reset, and I don't know why!
I've made the change now and will form a release shortly!
